-- NFA full seed: users, authorities, workflows, NAAC metrics
-- Password for all demo users: password123

-- Users
INSERT INTO users (id, "employeeId", email, "passwordHash", "firstName", "lastName", "roleId", "departmentId", "designationId", "positionId") VALUES ('usr_fac_cse', 'FAC001', 'faculty.cse@gcu.edu.in', '$2b$10$NcbOaU/.KVc.L/lfFy2A9OryfNO5E10uB3sS2UNxRwH1D.sqyRM6i', 'Raj', 'Kumar', 'role_faculty', 'dept_cs', 'des_faculty', 'pos_asst_prof') ON CONFLICT (email) DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName", "roleId" = EXCLUDED."roleId", "departmentId" = EXCLUDED."departmentId", "designationId" = EXCLUDED."designationId", "positionId" = EXCLUDED."positionId";
INSERT INTO users (id, "employeeId", email, "passwordHash", "firstName", "lastName", "roleId", "departmentId", "designationId", "positionId") VALUES ('usr_fac_cs2', 'FAC002', 'faculty.cs2@gcu.edu.in', '$2b$10$NcbOaU/.KVc.L/lfFy2A9OryfNO5E10uB3sS2UNxRwH1D.sqyRM6i', 'Anita', 'Desai', 'role_faculty', 'dept_cs', 'des_faculty', 'pos_asst_prof') ON CONFLICT (email) DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName", "roleId" = EXCLUDED."roleId", "departmentId" = EXCLUDED."departmentId", "designationId" = EXCLUDED."designationId", "positionId" = EXCLUDED."positionId";
INSERT INTO users (id, "employeeId", email, "passwordHash", "firstName", "lastName", "roleId", "departmentId", "designationId", "positionId") VALUES ('usr_hod_cse', 'HOD001', 'hod.cse@gcu.edu.in', '$2b$10$NcbOaU/.KVc.L/lfFy2A9OryfNO5E10uB3sS2UNxRwH1D.sqyRM6i', 'Priya', 'Sharma', 'role_hod', 'dept_cs', 'des_hod', 'pos_prof') ON CONFLICT (email) DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName", "roleId" = EXCLUDED."roleId", "departmentId" = EXCLUDED."departmentId", "designationId" = EXCLUDED."designationId", "positionId" = EXCLUDED."positionId";
INSERT INTO users (id, "employeeId", email, "passwordHash", "firstName", "lastName", "roleId", "departmentId", "designationId", "positionId") VALUES ('usr_fac_phy', 'FACPHY001', 'faculty.phy@gcu.edu.in', '$2b$10$NcbOaU/.KVc.L/lfFy2A9OryfNO5E10uB3sS2UNxRwH1D.sqyRM6i', 'Chidanand', 'Shinde', 'role_faculty', 'dept_phy', 'des_faculty', 'pos_asst_prof') ON CONFLICT (email) DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName", "roleId" = EXCLUDED."roleId", "departmentId" = EXCLUDED."departmentId", "designationId" = EXCLUDED."designationId", "positionId" = EXCLUDED."positionId";
INSERT INTO users (id, "employeeId", email, "passwordHash", "firstName", "lastName", "roleId", "departmentId", "designationId", "positionId") VALUES ('usr_fac_phy2', 'FACPHY002', 'faculty.phy2@gcu.edu.in', '$2b$10$NcbOaU/.KVc.L/lfFy2A9OryfNO5E10uB3sS2UNxRwH1D.sqyRM6i', 'Meena', 'Kulkarni', 'role_faculty', 'dept_phy', 'des_faculty', 'pos_prof') ON CONFLICT (email) DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName", "roleId" = EXCLUDED."roleId", "departmentId" = EXCLUDED."departmentId", "designationId" = EXCLUDED."designationId", "positionId" = EXCLUDED."positionId";
INSERT INTO users (id, "employeeId", email, "passwordHash", "firstName", "lastName", "roleId", "departmentId", "designationId", "positionId") VALUES ('usr_hod_phy', 'HODPHY001', 'hod.phy@gcu.edu.in', '$2b$10$NcbOaU/.KVc.L/lfFy2A9OryfNO5E10uB3sS2UNxRwH1D.sqyRM6i', 'Ravi', 'Patil', 'role_hod', 'dept_phy', 'des_hod', 'pos_prof') ON CONFLICT (email) DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName", "roleId" = EXCLUDED."roleId", "departmentId" = EXCLUDED."departmentId", "designationId" = EXCLUDED."designationId", "positionId" = EXCLUDED."positionId";
INSERT INTO users (id, "employeeId", email, "passwordHash", "firstName", "lastName", "roleId", "departmentId", "designationId", "positionId") VALUES ('usr_club', 'CLUB001', 'club.sports@gcu.edu.in', '$2b$10$NcbOaU/.KVc.L/lfFy2A9OryfNO5E10uB3sS2UNxRwH1D.sqyRM6i', 'Amit', 'Verma', 'role_club', 'dept_cs', 'des_faculty', 'pos_asst_prof') ON CONFLICT (email) DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName", "roleId" = EXCLUDED."roleId", "departmentId" = EXCLUDED."departmentId", "designationId" = EXCLUDED."designationId", "positionId" = EXCLUDED."positionId";
INSERT INTO users (id, "employeeId", email, "passwordHash", "firstName", "lastName", "roleId", "departmentId", "designationId", "positionId") VALUES ('usr_iqac', 'IQAC001', 'iqac@gcu.edu.in', '$2b$10$NcbOaU/.KVc.L/lfFy2A9OryfNO5E10uB3sS2UNxRwH1D.sqyRM6i', 'Sunita', 'Reddy', 'role_iqac', 'dept_iqac', NULL, NULL) ON CONFLICT (email) DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName", "roleId" = EXCLUDED."roleId", "departmentId" = EXCLUDED."departmentId", "designationId" = EXCLUDED."designationId", "positionId" = EXCLUDED."positionId";
INSERT INTO users (id, "employeeId", email, "passwordHash", "firstName", "lastName", "roleId", "departmentId", "designationId", "positionId") VALUES ('usr_pmseb', 'PMSEB001', 'pmseb@gcu.edu.in', '$2b$10$NcbOaU/.KVc.L/lfFy2A9OryfNO5E10uB3sS2UNxRwH1D.sqyRM6i', 'Vikram', 'Singh', 'role_pmseb', NULL, NULL, NULL) ON CONFLICT (email) DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName", "roleId" = EXCLUDED."roleId", "departmentId" = EXCLUDED."departmentId", "designationId" = EXCLUDED."designationId", "positionId" = EXCLUDED."positionId";
INSERT INTO users (id, "employeeId", email, "passwordHash", "firstName", "lastName", "roleId", "departmentId", "designationId", "positionId") VALUES ('usr_hr', 'HR001', 'hr@gcu.edu.in', '$2b$10$NcbOaU/.KVc.L/lfFy2A9OryfNO5E10uB3sS2UNxRwH1D.sqyRM6i', 'Meera', 'Krishnan', 'role_hr', NULL, NULL, NULL) ON CONFLICT (email) DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName", "roleId" = EXCLUDED."roleId", "departmentId" = EXCLUDED."departmentId", "designationId" = EXCLUDED."designationId", "positionId" = EXCLUDED."positionId";
INSERT INTO users (id, "employeeId", email, "passwordHash", "firstName", "lastName", "roleId", "departmentId", "designationId", "positionId") VALUES ('usr_coe', 'COE001', 'coe@gcu.edu.in', '$2b$10$NcbOaU/.KVc.L/lfFy2A9OryfNO5E10uB3sS2UNxRwH1D.sqyRM6i', 'Lakshmi', 'Nair', 'role_coe', 'dept_exam', NULL, NULL) ON CONFLICT (email) DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName", "roleId" = EXCLUDED."roleId", "departmentId" = EXCLUDED."departmentId", "designationId" = EXCLUDED."designationId", "positionId" = EXCLUDED."positionId";
INSERT INTO users (id, "employeeId", email, "passwordHash", "firstName", "lastName", "roleId", "departmentId", "designationId", "positionId") VALUES ('usr_reg', 'REG001', 'registrar@gcu.edu.in', '$2b$10$NcbOaU/.KVc.L/lfFy2A9OryfNO5E10uB3sS2UNxRwH1D.sqyRM6i', 'Anil', 'Menon', 'role_registrar', 'dept_reg', NULL, NULL) ON CONFLICT (email) DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName", "roleId" = EXCLUDED."roleId", "departmentId" = EXCLUDED."departmentId", "designationId" = EXCLUDED."designationId", "positionId" = EXCLUDED."positionId";
INSERT INTO users (id, "employeeId", email, "passwordHash", "firstName", "lastName", "roleId", "departmentId", "designationId", "positionId") VALUES ('usr_ofc', 'OFC001', 'ofc@gcu.edu.in', '$2b$10$NcbOaU/.KVc.L/lfFy2A9OryfNO5E10uB3sS2UNxRwH1D.sqyRM6i', 'Deepa', 'Iyer', 'role_ofc', NULL, NULL, NULL) ON CONFLICT (email) DO UPDATE SET "passwordHash" = EXCLUDED."passwordHash", "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName", "roleId" = EXCLUDED."roleId", "departmentId" = EXCLUDED."departmentId", "designationId" = EXCLUDED."designationId", "positionId" = EXCLUDED."positionId";

-- HOD assignments
UPDATE departments SET "hodId" = 'usr_hod_cse' WHERE id = 'dept_cs';
UPDATE departments SET "hodId" = 'usr_hod_phy' WHERE id = 'dept_phy';

-- Club authority
INSERT INTO club_authorities (id, "clubId", "userId") VALUES ('ca_sports', 'club_sports', 'usr_club') ON CONFLICT ("clubId", "userId") DO UPDATE SET "isActive" = TRUE;

-- Authority mapping
INSERT INTO authority_mapping (id, "roleCode", "userId", "assignmentType", "isActive") VALUES ('am_iqac', 'IQAC', 'usr_iqac', 'PERMANENT', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO authority_mapping (id, "roleCode", "userId", "assignmentType", "isActive") VALUES ('am_pmseb', 'PMSEB', 'usr_pmseb', 'PERMANENT', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO authority_mapping (id, "roleCode", "userId", "assignmentType", "isActive") VALUES ('am_hr', 'HR', 'usr_hr', 'PERMANENT', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO authority_mapping (id, "roleCode", "userId", "assignmentType", "isActive") VALUES ('am_coe', 'COE', 'usr_coe', 'PERMANENT', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO authority_mapping (id, "roleCode", "userId", "assignmentType", "isActive") VALUES ('am_reg', 'REGISTRAR', 'usr_reg', 'PERMANENT', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO authority_mapping (id, "roleCode", "userId", "assignmentType", "isActive") VALUES ('am_ofc', 'OFC', 'usr_ofc', 'PERMANENT', TRUE) ON CONFLICT DO NOTHING;

-- Approval workflow
INSERT INTO approval_workflow (id, category, "stepOrder", "roleCode", "stepLabel") VALUES ('aw_acad_1', 'ACADEMIC', 1, 'HOD', 'HOD Approval') ON CONFLICT (category, "stepOrder") DO UPDATE SET "roleCode" = EXCLUDED."roleCode", "stepLabel" = EXCLUDED."stepLabel";
INSERT INTO approval_workflow (id, category, "stepOrder", "roleCode", "stepLabel") VALUES ('aw_acad_2', 'ACADEMIC', 2, 'IQAC', 'IQAC Approval') ON CONFLICT (category, "stepOrder") DO UPDATE SET "roleCode" = EXCLUDED."roleCode", "stepLabel" = EXCLUDED."stepLabel";
INSERT INTO approval_workflow (id, category, "stepOrder", "roleCode", "stepLabel") VALUES ('aw_acad_3', 'ACADEMIC', 3, 'PMSEB', 'PMSEB Approval') ON CONFLICT (category, "stepOrder") DO UPDATE SET "roleCode" = EXCLUDED."roleCode", "stepLabel" = EXCLUDED."stepLabel";
INSERT INTO approval_workflow (id, category, "stepOrder", "roleCode", "stepLabel") VALUES ('aw_acad_4', 'ACADEMIC', 4, 'COE', 'COE Approval') ON CONFLICT (category, "stepOrder") DO UPDATE SET "roleCode" = EXCLUDED."roleCode", "stepLabel" = EXCLUDED."stepLabel";
INSERT INTO approval_workflow (id, category, "stepOrder", "roleCode", "stepLabel") VALUES ('aw_acad_5', 'ACADEMIC', 5, 'REGISTRAR', 'Registrar Approval') ON CONFLICT (category, "stepOrder") DO UPDATE SET "roleCode" = EXCLUDED."roleCode", "stepLabel" = EXCLUDED."stepLabel";
INSERT INTO approval_workflow (id, category, "stepOrder", "roleCode", "stepLabel") VALUES ('aw_acad_6', 'ACADEMIC', 6, 'OFC', 'OFC Final Approval') ON CONFLICT (category, "stepOrder") DO UPDATE SET "roleCode" = EXCLUDED."roleCode", "stepLabel" = EXCLUDED."stepLabel";
INSERT INTO approval_workflow (id, category, "stepOrder", "roleCode", "stepLabel") VALUES ('aw_club_1', 'CLUB', 1, 'CLUB_AUTHORITY', 'Club Authority') ON CONFLICT (category, "stepOrder") DO UPDATE SET "roleCode" = EXCLUDED."roleCode", "stepLabel" = EXCLUDED."stepLabel";
INSERT INTO approval_workflow (id, category, "stepOrder", "roleCode", "stepLabel") VALUES ('aw_club_2', 'CLUB', 2, 'IQAC', 'IQAC Approval') ON CONFLICT (category, "stepOrder") DO UPDATE SET "roleCode" = EXCLUDED."roleCode", "stepLabel" = EXCLUDED."stepLabel";
INSERT INTO approval_workflow (id, category, "stepOrder", "roleCode", "stepLabel") VALUES ('aw_club_3', 'CLUB', 3, 'PMSEB', 'PMSEB Approval') ON CONFLICT (category, "stepOrder") DO UPDATE SET "roleCode" = EXCLUDED."roleCode", "stepLabel" = EXCLUDED."stepLabel";
INSERT INTO approval_workflow (id, category, "stepOrder", "roleCode", "stepLabel") VALUES ('aw_club_4', 'CLUB', 4, 'COE', 'COE Approval') ON CONFLICT (category, "stepOrder") DO UPDATE SET "roleCode" = EXCLUDED."roleCode", "stepLabel" = EXCLUDED."stepLabel";
INSERT INTO approval_workflow (id, category, "stepOrder", "roleCode", "stepLabel") VALUES ('aw_club_5', 'CLUB', 5, 'REGISTRAR', 'Registrar Approval') ON CONFLICT (category, "stepOrder") DO UPDATE SET "roleCode" = EXCLUDED."roleCode", "stepLabel" = EXCLUDED."stepLabel";
INSERT INTO approval_workflow (id, category, "stepOrder", "roleCode", "stepLabel") VALUES ('aw_club_6', 'CLUB', 6, 'OFC', 'OFC Final Approval') ON CONFLICT (category, "stepOrder") DO UPDATE SET "roleCode" = EXCLUDED."roleCode", "stepLabel" = EXCLUDED."stepLabel";

-- Workflow templates
INSERT INTO workflow_templates (id, name, category, "academicSection", steps, "isDefault") VALUES ('wt_dept', 'Department — HOD → IQAC → PMSEB → Registrar', 'ACADEMIC', 'DEPT', '["HOD","IQAC","PMSEB"]'::jsonb, false) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, steps = EXCLUDED.steps, "isDefault" = EXCLUDED."isDefault";
INSERT INTO workflow_templates (id, name, category, "academicSection", steps, "isDefault") VALUES ('wt_acad_def', 'Academic — IQAC → PMSEB → Registrar', 'ACADEMIC', NULL, '["IQAC","PMSEB"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, steps = EXCLUDED.steps, "isDefault" = EXCLUDED."isDefault";
INSERT INTO workflow_templates (id, name, category, "academicSection", steps, "isDefault") VALUES ('wt_gen', 'Academic — IQAC → Registrar', 'ACADEMIC', 'GEN', '["IQAC"]'::jsonb, false) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, steps = EXCLUDED.steps, "isDefault" = EXCLUDED."isDefault";
INSERT INTO workflow_templates (id, name, category, "academicSection", steps, "isDefault") VALUES ('wt_exo', 'Academic — PMSEB → Registrar', 'ACADEMIC', 'EXO', '["PMSEB"]'::jsonb, false) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, steps = EXCLUDED.steps, "isDefault" = EXCLUDED."isDefault";
INSERT INTO workflow_templates (id, name, category, "academicSection", steps, "isDefault") VALUES ('wt_hr', 'HR section — HR → IQAC → PMSEB → COE', 'ACADEMIC', 'HR', '["HR","IQAC","PMSEB","COE"]'::jsonb, false) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, steps = EXCLUDED.steps, "isDefault" = EXCLUDED."isDefault";
INSERT INTO workflow_templates (id, name, category, "academicSection", steps, "isDefault") VALUES ('wt_coe', 'COE section — COE → IQAC → PMSEB', 'ACADEMIC', 'COE', '["COE","IQAC","PMSEB"]'::jsonb, false) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, steps = EXCLUDED.steps, "isDefault" = EXCLUDED."isDefault";
INSERT INTO workflow_templates (id, name, category, "academicSection", steps, "isDefault") VALUES ('wt_club', 'Club — Club Authority → IQAC → PMSEB → Registrar', 'CLUB', NULL, '["CLUB_AUTHORITY","IQAC","PMSEB"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, steps = EXCLUDED.steps, "isDefault" = EXCLUDED."isDefault";

-- NAAC criteria & metrics
INSERT INTO naac_criteria (id, number, title, "inputProcessOutcome", "sortOrder") VALUES ('nc_1', 1, 'Curriculum Design', 'INPUT', 1) ON CONFLICT (number) DO UPDATE SET title = EXCLUDED.title, "inputProcessOutcome" = EXCLUDED."inputProcessOutcome", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_1_1', '1.1', 'Outcome-based curriculum', 'Curriculum framework is aligned to Program Outcomes (POs), Program Specific Outcomes (PSOs) and Course Outcomes (COs).', 'nc_1', 0) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_1_2', '1.2', 'Stakeholder Participation', 'Stakeholders including students, alumni, employers and faculty participate in curriculum design and review.', 'nc_1', 1) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_1_3', '1.3', 'Curriculum Flexibility', 'Curriculum provides flexibility, choice-based credit system and multiple entry/exit options where applicable.', 'nc_1', 2) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_1_4', '1.4', 'Skill Orientation', 'Curriculum integrates employability, entrepreneurship and life skills through structured components.', 'nc_1', 3) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_1_5', '1.5', 'Multidisciplinary approach', 'Programs encourage multidisciplinary and interdisciplinary learning through courses and projects.', 'nc_1', 4) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_1_6', '1.6', 'Academic calendar adherence', 'Academic calendar is prepared and adhered to for timely completion of academic activities.', 'nc_1', 5) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_1_7', '1.7', 'Feedback on curriculum', 'Structured feedback on curriculum is collected from stakeholders and used for revision.', 'nc_1', 6) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_1_8', '1.8', 'Curriculum enrichment', 'Value-added and enrichment courses supplement the core curriculum for holistic development.', 'nc_1', 7) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO naac_criteria (id, number, title, "inputProcessOutcome", "sortOrder") VALUES ('nc_2', 2, 'Faculty Resources', 'INPUT', 2) ON CONFLICT (number) DO UPDATE SET title = EXCLUDED.title, "inputProcessOutcome" = EXCLUDED."inputProcessOutcome", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_2_1', '2.1', 'Recruitment', 'Faculty recruitment practices follow UGC/AICTE/State norms with transparency and merit-based selection.', 'nc_2', 0) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_2_2', '2.2', 'Pay and Allowances', 'Faculty are paid as per statutory norms with timely disbursement of salary and allowances.', 'nc_2', 1) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_2_3', '2.3', 'Faculty Development', 'Faculty participate in professional development programs, FDPs, seminars and workshops.', 'nc_2', 2) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_2_4', '2.4', 'Faculty Diversity', 'Institution maintains diversity in faculty recruitment across gender and categories.', 'nc_2', 3) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_2_5', '2.5', 'Faculty Retention', 'Measures are in place to retain qualified faculty and reduce attrition.', 'nc_2', 4) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_2_6', '2.6', 'Faculty Student Ratio', 'Faculty-student ratio is maintained as per regulatory requirements for quality teaching.', 'nc_2', 5) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO naac_criteria (id, number, title, "inputProcessOutcome", "sortOrder") VALUES ('nc_3', 3, 'Infrastructure', 'INPUT', 3) ON CONFLICT (number) DO UPDATE SET title = EXCLUDED.title, "inputProcessOutcome" = EXCLUDED."inputProcessOutcome", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_3_1', '3.1', 'Physical Infrastructure', 'Adequate classrooms, laboratories, seminar halls and administrative spaces are available.', 'nc_3', 0) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_3_2', '3.2', 'Learning Resources', 'Library, e-resources, journals and learning materials support academic programs.', 'nc_3', 1) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_3_3', '3.3', 'IT Infrastructure', 'Computing facilities, internet connectivity and digital tools support teaching and administration.', 'nc_3', 2) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_3_4', '3.4', 'Innovation Resources', 'Incubation, maker spaces and innovation facilities support student and faculty projects.', 'nc_3', 3) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_3_5', '3.5', 'Maintenance of infrastructure', 'Infrastructure is maintained through periodic upkeep and annual maintenance budgets.', 'nc_3', 4) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_3_6', '3.6', 'Optimal usage of infrastructure', 'Physical and digital infrastructure is utilized optimally through scheduling and monitoring.', 'nc_3', 5) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO naac_criteria (id, number, title, "inputProcessOutcome", "sortOrder") VALUES ('nc_4', 4, 'Financial Resources & Management', 'INPUT', 4) ON CONFLICT (number) DO UPDATE SET title = EXCLUDED.title, "inputProcessOutcome" = EXCLUDED."inputProcessOutcome", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_4_1', '4.1', 'Capital Income', 'Capital grants and funding are mobilized for infrastructure and development projects.', 'nc_4', 0) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_4_2', '4.2', 'Revenue Expenditure', 'Revenue expenditure on academic and administrative activities is planned and monitored.', 'nc_4', 1) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_4_3', '4.3', 'Financial Controls & Risk Management', 'Internal controls, audits and risk management practices ensure financial integrity.', 'nc_4', 2) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_4_4', '4.4', 'Internal and external audit', 'Regular internal and external audits are conducted and findings are acted upon.', 'nc_4', 3) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_4_5', '4.5', 'Budget allocation and utilization', 'Budgets are allocated department-wise and utilization is tracked against plans.', 'nc_4', 4) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_4_6', '4.6', 'Resource mobilization', 'Institution mobilizes funds through grants, donations, consultancy and other sources.', 'nc_4', 5) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO naac_criteria (id, number, title, "inputProcessOutcome", "sortOrder") VALUES ('nc_5', 5, 'Learning & Teaching', 'PROCESS', 5) ON CONFLICT (number) DO UPDATE SET title = EXCLUDED.title, "inputProcessOutcome" = EXCLUDED."inputProcessOutcome", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_5_1', '5.1', 'Pedagogical Approaches', 'Student-centric pedagogical approaches including active learning are practiced in classrooms.', 'nc_5', 0) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_5_2', '5.2', 'Internships', 'Students undertake internships, field projects and industry exposure as part of learning.', 'nc_5', 1) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_5_3', '5.3', 'Assessment', 'Continuous assessment, rubrics and outcome-based evaluation methods are implemented.', 'nc_5', 2) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_5_4', '5.4', 'Learning Management System', 'LMS and digital platforms support course delivery, assignments and student engagement.', 'nc_5', 3) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_5_5', '5.5', 'Student-centric methods', 'Teaching methods address diverse learning needs through tutorials, mentoring and remedial support.', 'nc_5', 4) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_5_6', '5.6', 'Experiential learning', 'Experiential learning through labs, projects and practical work reinforces theoretical concepts.', 'nc_5', 5) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_5_7', '5.7', 'Continuous internal evaluation', 'Internal evaluation is continuous, transparent and aligned with course outcomes.', 'nc_5', 6) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO naac_criteria (id, number, title, "inputProcessOutcome", "sortOrder") VALUES ('nc_6', 6, 'Extended Curricular Engagements', 'PROCESS', 6) ON CONFLICT (number) DO UPDATE SET title = EXCLUDED.title, "inputProcessOutcome" = EXCLUDED."inputProcessOutcome", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_6_1', '6.1', 'Technical/Domain Clubs', 'Technical and domain clubs promote peer learning, competitions and skill development.', 'nc_6', 0) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_6_2', '6.2', 'Hackathons', 'Hackathons, coding events and innovation challenges engage students beyond the curriculum.', 'nc_6', 1) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_6_3', '6.3', 'Cultural Clubs', 'Cultural clubs and activities foster creativity, teamwork and inclusive participation.', 'nc_6', 2) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_6_4', '6.4', 'Sports Clubs and Activities', 'Sports clubs and activities promote physical fitness and institutional sports culture.', 'nc_6', 3) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_6_5', '6.5', 'Sports participation and institutional achievements', 'Sports participation and institutional achievements in inter-collegiate events are documented.', 'nc_6', 4) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_6_6', '6.6', 'Extended Curricular Engagements', 'Extended curricular engagements including NSS, NCC and outreach complement formal learning.', 'nc_6', 5) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO naac_criteria (id, number, title, "inputProcessOutcome", "sortOrder") VALUES ('nc_7', 7, 'Governance & Administration', 'PROCESS', 7) ON CONFLICT (number) DO UPDATE SET title = EXCLUDED.title, "inputProcessOutcome" = EXCLUDED."inputProcessOutcome", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_7_1', '7.1', 'Statutory Compliance', 'Institution complies with statutory bodies, affiliating university and regulatory requirements.', 'nc_7', 0) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_7_2', '7.2', 'E-Governance', 'E-governance systems support admissions, examinations, finance and administration.', 'nc_7', 1) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_7_3', '7.3', 'Student & Employee Welfare', 'Welfare measures for students and employees include scholarships, health and support services.', 'nc_7', 2) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_7_4', '7.4', 'Effective Leadership', 'Leadership provides vision, decentralization and participatory decision-making.', 'nc_7', 3) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_7_5', '7.5', 'Quality Assurance System', 'IQAC and internal quality assurance mechanisms monitor and improve institutional processes.', 'nc_7', 4) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_7_6', '7.6', 'Strategic plan and deployment', 'Strategic plan is documented, communicated and deployed through actionable initiatives.', 'nc_7', 5) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_7_7', '7.7', 'Transparent admission process', 'Admissions follow transparent, merit-based and documented procedures.', 'nc_7', 6) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_7_8', '7.8', 'Grievance redressal', 'Grievance redressal mechanisms address student and staff concerns in a time-bound manner.', 'nc_7', 7) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO naac_criteria (id, number, title, "inputProcessOutcome", "sortOrder") VALUES ('nc_8', 8, 'Student Outcomes', 'OUTCOME', 8) ON CONFLICT (number) DO UPDATE SET title = EXCLUDED.title, "inputProcessOutcome" = EXCLUDED."inputProcessOutcome", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_8_1', '8.1', 'Academic Progression', 'Students progress academically with acceptable pass rates and progression to higher semesters.', 'nc_8', 0) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_8_2', '8.2', 'Placement and Employment', 'Graduates secure placements, entrepreneurship or meaningful employment after completion.', 'nc_8', 1) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_8_3', '8.3', 'Competitive Exams', 'Students qualify in competitive examinations and professional certification tests.', 'nc_8', 2) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_8_4', '8.4', 'Graduation Rate', 'Graduation rate reflects successful completion of programs within stipulated time.', 'nc_8', 3) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_8_5', '8.5', 'Higher education progression', 'Graduates pursue higher education in reputed institutions in India and abroad.', 'nc_8', 4) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_8_6', '8.6', 'Alumni engagement', 'Alumni contribute through mentoring, placements, feedback and institutional support.', 'nc_8', 5) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_8_7', '8.7', 'Student satisfaction', 'Student satisfaction surveys inform improvements in teaching, facilities and services.', 'nc_8', 6) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_8_8', '8.8', 'Awards and recognition', 'Students receive awards and recognition in academic, sports and co-curricular domains.', 'nc_8', 7) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO naac_criteria (id, number, title, "inputProcessOutcome", "sortOrder") VALUES ('nc_9', 9, 'Research & Innovation Outcomes', 'OUTCOME', 9) ON CONFLICT (number) DO UPDATE SET title = EXCLUDED.title, "inputProcessOutcome" = EXCLUDED."inputProcessOutcome", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_9_1', '9.1', 'External Research Grants', 'Faculty mobilize external research grants from funding agencies and industry.', 'nc_9', 0) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_9_2', '9.2', 'Research Publications', 'Research publications in peer-reviewed journals and conferences are documented.', 'nc_9', 1) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_9_3', '9.3', 'PhDs Awarded', 'PhDs awarded under faculty guidance contribute to research capacity building.', 'nc_9', 2) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_9_4', '9.4', 'IPRs Produced', 'Patents, copyrights and other IPRs generated reflect innovation outcomes.', 'nc_9', 3) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_9_5', '9.5', 'Research projects', 'Ongoing and completed research projects address societal and academic challenges.', 'nc_9', 4) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_9_6', '9.6', 'Consultancy and extension', 'Faculty undertake consultancy and extension activities benefiting stakeholders.', 'nc_9', 5) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_9_7', '9.7', 'Research facilities', 'Research laboratories and facilities support faculty and student research.', 'nc_9', 6) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_9_8', '9.8', 'Collaborations for research', 'MoUs and collaborations with industry and academia strengthen research ecosystem.', 'nc_9', 7) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO naac_criteria (id, number, title, "inputProcessOutcome", "sortOrder") VALUES ('nc_10', 10, 'Sustainability Outcomes', 'OUTCOME', 10) ON CONFLICT (number) DO UPDATE SET title = EXCLUDED.title, "inputProcessOutcome" = EXCLUDED."inputProcessOutcome", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_10_1', '10.1', 'Community Activities', 'Community engagement and outreach programs address local developmental needs.', 'nc_10', 0) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_10_2', '10.2', 'Waste and Water Management', 'Waste segregation, recycling and water conservation practices are implemented on campus.', 'nc_10', 1) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_10_3', '10.3', 'Green Audits and Initiatives', 'Green audits and environmental initiatives promote sustainable campus operations.', 'nc_10', 2) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_10_4', '10.4', 'Environmental consciousness', 'Programs build environmental consciousness among students and staff.', 'nc_10', 3) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;
INSERT INTO metrics (id, code, title, description, "criterionId", "sortOrder") VALUES ('m_10_5', '10.5', 'Industry/NGO Collaborations', 'Collaborations with industry and NGOs support sustainability and social impact projects.', 'nc_10', 4) ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, "criterionId" = EXCLUDED."criterionId", "isActive" = TRUE;